name: Deploy Javadoc

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          javadoc-branch: javadoc
          java-version: 11
          target-folder: javadoc
